---
- name: Download the nodejs binary tarball
  get_url:
    url: "http://nodejs.org/download/release/latest-v8.x/{{ node_package }}.tar.gz"
    dest: /usr/local

- name: Unarchive the nodejs tarball
  unarchive:
    src: /usr/local/{{ node_package }}.tar.gz
    dest: /usr/local
    copy: no

- name: Link nodejs binaries
  file:
    src: "/usr/local/{{ node_package }}/bin/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    state: link
    force: true
  with_items:
    - node
    - npm
