set nocompatible

" Disable .swp files
set noswapfile

" Load plugins
""""""""""""""
call plug#begin('~/.vim/plugged')
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
Plug 'christoomey/vim-tmux-navigator'
Plug 'itchyny/lightline.vim'
Plug 'scrooloose/nerdtree'
Plug 'w0rp/ale'
Plug 'mileszs/ack.vim'
call plug#end()

" Tabs & indentation
set expandtab
set shiftwidth=2
set softtabstop=2

" Solarized theme
"""""""""""""""""
syntax enable
set background=dark
colorscheme solarized

" Key bindings
""""""""""""""

" Change leader to a comma because the backslash is too far away
" That means all \x commands turn into ,x
" The mapleader has to be set before vundle starts loading all 
" the plugins.
let mapleader=","

" Key bindings - Search files
nnoremap <silent> <leader>f :FZF<CR>"

" Key bindings - NERDtree
nmap <leader>n :NERDTreeToggle<cr>

" Key bindings - Misc

" escapes from insert mode
imap jk <esc>
imap kj <esc>
imap <C-s> <esc>:w<cr>

" Bind `t` to go to topic in help files
autocmd Filetype help nnoremap t <C-]>
autocmd Filetype help nnoremap <buffer> q :q<CR>

" Plugins config
""""""""""""""""

" Plugin - lightline
set laststatus=2
let g:lightline = {
  \ 'colorscheme': 'solarized',
  \ }

" Plugin - vim.ack
" Using ag instead of Ack
if executable('ag')
  let g:ackprg = 'ag --vimgrep --smart-case'
endif
cnoreabbrev ag Ack
cnoreabbrev aG Ack
cnoreabbrev Ag Ack
cnoreabbrev AG Ack
