" Disable .swp files
set noswapfile

" Load plugins
call plug#begin('~/.vim/plugged')
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
call plug#end()

" Key bindings

" Key bindings - Search files
nnoremap <silent> ,f :FZF<CR>

