#
# Executes commands at the start of an interactive session.
#
export TERM=xterm-256color

# Set variables for Prezto
source "${ZDOTDIR:-$HOME}/.myenv/configuration/zprezto_pre_init.zsh"

# Source Prezto
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize
source "${ZDOTDIR:-$HOME}/.myenv/configuration/zsh.zsh"
