
#
# Executes commands at the start of an interactive session.
#
export TERM=xterm-256color
export VISUAL=vim
export EDITOR="$VISUAL"

# Use the correct font icons (must be before prezto/init)
POWERLEVEL9K_MODE='awesome-patched'

# Source Prezto
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Source fzf.zsh
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Source font variables
source "${ZDOTDIR:-$HOME}/.myenv/fonts/Droid+Sans+Mono+Awesome.sh"

# ==================
# ZSH: customization

# zsh - prompt
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(dir vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status)
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=''

# zsh - prompt - segments - dir
POWERLEVEL9K_SHORTEN_DIR_LENGTH=2
POWERLEVEL9K_SHORTEN_STRATEGY=truncate_from_right
POWERLEVEL9K_SHORTEN_DELIMITER=';'

# zsh - prompt - segments - vcs
POWERLEVEL9K_VCS_CLEAN_FOREGROUND='black'
POWERLEVEL9K_VCS_CLEAN_BACKGROUND='green'
POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND='black'
POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND='yellow'
POWERLEVEL9K_VCS_MODIFIED_FOREGROUND='black'
POWERLEVEL9K_VCS_MODIFIED_BACKGROUND='red'

# zsh - prompt - segments - status
POWERLEVEL9K_STATUS_VERBOSE=false
POWERLEVEL9K_STATUS_ERROR_FOREGROUND='red'

# ZSH: customization - END
# ========================

# ============================================
# TMUX: session sharing, autostart and aliases

export TMUX_SOCKET=/tmp/tmux_default_socket
export TMUX_DEFAULT_SESSION=main

# Use a default socket for tmux commands. Enables sharing
# tmux over several SSH connetions and keeps the server
# active when disconnecting.
_tmux_use_socket="-S $TMUX_SOCKET"
alias tmux='tmux -S /tmp/tmux_default_socket'

# Creating new session or attaching to existing one
# if not already in tmux.
# Using exec gives control to tmux, exiting the
# session (and thus the SSH if connected over SSH)
# when detaching.
if [[ -z "$TMUX" ]]; then
	if ! tmux has-session 2> /dev/null; then
		exec tmux new-session -s $TMUX_DEFAULT_SESSION
	else
		exec tmux attach-session -t $TMUX_DEFAULT_SESSION
	fi
fi

# TMUX: session sharing, autostart and aliases - END
# ==================================================

# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin"
