#
# Executes commands at the start of an interactive session.
#
export TERM=xterm-256color
export VISUAL=vim
export EDITOR="$VISUAL"

# Must be before .zprezto/init.sh
POWERLEVEL9K_MODE='awesome-patched'

# Source Prezto
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Source fzf.zsh
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Source font variables
source "${ZDOTDIR:-$HOME}/.myenv/fonts/Droid+Sans+Mono+Awesome.sh"

# =============
# Customize zsh
# =============

# zsh - prompt
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(dir vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status)
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=''

# zsh - prompt - segments - dir
POWERLEVEL9K_SHORTEN_DIR_LENGTH=2
POWERLEVEL9K_SHORTEN_STRATEGY=truncate_from_right
POWERLEVEL9K_SHORTEN_DELIMITER=';'

# zsh - prompt - segments - vcs
POWERLEVEL9K_VCS_CLEAN_FOREGROUND='black'
POWERLEVEL9K_VCS_CLEAN_BACKGROUND='green'
POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND='black'
POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND='yellow'
POWERLEVEL9K_VCS_MODIFIED_FOREGROUND='black'
POWERLEVEL9K_VCS_MODIFIED_BACKGROUND='red'

# zsh - prompt - segments - status
POWERLEVEL9K_STATUS_VERBOSE=false
POWERLEVEL9K_STATUS_ERROR_FOREGROUND='red'

# ===================
# Customize zsh - END
# ===================
