---

- name: Source go-bin.sh
  shell: source /etc/profile.d/go-bin.sh
  args:
    executable: /bin/bash

- name: Install some additions for Golang
  command: go get -u github.com/nsf/gocode

- name: Install vim-go binaries
  command: vim +GoInstallBinaries +qall

