---

- hosts: all

  vars:
    guest_user: "ubuntu"
    zsh_user: "{{ guest_user }}"
    vagrant_dir: "/vagrant"
    myenv_dir: "{{ ansible_env.HOME }}/.myenv"

  roles:
    - system
    - zsh
    - vim
    - { role: rvm1-ansible,
        tags: ruby,
        rvm1_rubies: ["ruby-2.4", "ruby-2.3"],
        rvm1_user: "{{ guest_user }}"
      }
    - {
        role: ansible-go,
        become: yes
      }
    - {
        role: ansible-nvm,
        nvm: {
          user: "{{ guest_user }}",
          version: 'v0.33.2',
          node_version: 'v6.11.0'
        }
      }
    - vim_plugins
    - node_modules

  tasks:
    - include: tasks/timezone.yml
    - include: tasks/reset_runcoms.yml

