# Security parts from http://ryaneschinger.com/blog/securing-a-server-with-ansible/
---
- hosts: all

  vars:
    ubuntu_common_required_packages:
      - fail2ban
      - ufw
      - unattended-upgrades

    ubuntu_common_optional_packages:
      - mosh

    ubuntu_common_ssh_port: 6677
    ubuntu_common_mosh_from_port: 60000
    ubuntu_common_mosh_to_port: 60010

  tasks:
    - name: Ensure aptitude is installed
      apt: state=installed pkg=aptitude
      become: true

    - name: Update APT package cache
      apt: update_cache=yes cache_valid_time=3600
      become: true

    - name: Upgrade APT to the latest packages
      apt: upgrade=safe
      become: true

    - name: Install required packages
      apt: state=installed pkg={{ item }}
      with_items: "{{ ubuntu_common_required_packages }}"
      become: true

    - name: Install optional packages
      apt: state=installed pkg={{ item }}
      with_items: "{{ ubuntu_common_required_packages }}"
      become: true

    - name: Adjust APT update intervals
      copy: src=support/apt_periodic dest=/etc/apt/apt.conf.d/10periodic
      become: true

    - name: Allow ssh traffic
      ufw: rule=allow port="{{ ubuntu_common_ssh_port }}" proto=tcp
      become: true

    - name: Setup ufw
      ufw: state=enabled policy=deny
      become: true

    - name: Allow mosh traffic
      ufw: rule=allow proto=udp port="{{ ubuntu_common_mosh_from_port }}:{{ ubuntu_common_mosh_to_port }}"
      when: "'mosh' in ubuntu_common_optional_packages"
      become: true

    - name: Disallow password authentication
      lineinfile: dest=/etc/ssh/sshd_config
                  regexp="^PasswordAuthentication"
                  line="PasswordAuthentication no"
                  state=present
      # notify: Restart ssh # only restarting for the last task
      become: true

    - name: Disallow root SSH access
      lineinfile: dest=/etc/ssh/sshd_config
                  regexp="^PermitRootLogin"
                  line="PermitRootLogin no"
                  state=present
      # notify: Restart ssh # only restarting for the last task
      become: true

    - name: Enable key forwarding
      lineinfile: dest=/etc/ssh/sshd_config
                   regexp="^AllowAgentForwarding"
                   line="AllowAgentForwarding yes"
                   state=present
      notify: Restart ssh
      become: true

  handlers:
    - name: Restart ssh
      service: name=ssh state=restarted
      become: true
