---

- hosts: all
  pre_tasks:
    - include_vars: "{{ item }}"
      with_fileglob:
        - playbook_config.yml
      tags: ['always']

  roles:
    - system
    - zsh
    - rupa_z
    - vim
    - role: ansible-rbenv-role
      rbenv:
        env: user
        default_ruby: 2.4.2
        rubies:
          - version: 2.4.2
        become: true
    - development_packages
    - go_additions
    - vim_plugins

  tasks:
    - include: tasks/reset_runcoms.yml

