---

- name: Uninstall apt vim
  package:
    name: "{{ item }}"
    state: absent
  with_items:
    - vim
    - vim-runtime
    - gvim
    - vim-tiny
    - vim-common
    - vim-gui
    - vim-nox
  become: yes
  when: not env_macos

- name: Ensure build dependencies are installed
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - build-essential
    - gcc
    - libncurses-dev
  become: yes
  when: not env_macos

- name: Ensure vim dependencies are installed
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - libncurses-dev
  become: yes
  when: not env_macos

- name: Check if installed
  command: >
    vim --version
  register: vim_version
  ignore_errors: yes

- name: Download vim from git
  git:
    repo: https://github.com/vim/vim.git
    dest: /tmp/vim
    track_submodules: true
    force: true
    update: false
  when: (vim_version|failed or env_macos)
  # vim is installed by default on macOS and we won't uninstall it
  # like we did for ubuntu

- name: Install vim from source
  shell: >
    cd /tmp/vim &&
    ./configure --enable-pythoninterp=yes --enable-luainterp=yes &&
    make &&
    make install
  become: yes
  when: (vim_version|failed or env_macos)

- name: Create ~/.vim/autoload directory
  file: path="{{ ansible_env.HOME }}/.vim/autoload" state=directory

- name: Install vim-plug
  get_url:
    dest: ~/.vim/autoload/plug.vim
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

- name: Link ~/.vim/colors directory
  file:
    src: "{{ myenv_dir }}/configuration/vim/colors"
    dest: "{{ ansible_env.HOME }}/.vim/colors"
    state: link
    force: true
