---

- name: Check if installed
  command: >
    vim --version
  register: vim_version
  ignore_errors: yes

- name: Download vim from git
  git:
    repo: https://github.com/vim/vim.git
    dest: /tmp/vim
    track_submodules: true
    force: true
    update: false
  when: (vim_version is failed)

- name: Install vim from source
  shell: >
    cd /tmp/vim &&
    ./configure --enable-pythoninterp=yes --enable-luainterp=yes &&
    make &&
    make install
  become: yes
  when: (vim_version is failed)

- name: Create ~/.vim/autoload directory
  file: path="{{ ansible_env.HOME }}/.vim/autoload" state=directory

- name: Install vim-plug
  get_url:
    dest: ~/.vim/autoload/plug.vim
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

- name: Link ~/.vim/colors directory
  file:
    src: "{{ myenv_dir }}/configuration/vim/colors"
    dest: "{{ ansible_env.HOME }}/.vim/colors"
    state: link
    force: true
